INSERT INTO Categories VALUES("Finding a job/employment");
INSERT INTO Categories VALUES("Earning an advanced degree");
INSERT INTO Categories VALUES("Contributing to the success of an organization");
INSERT INTO Categories VALUES("Being/becoming an entrepeneur");
INSERT INTO Categories VALUES("Achieving recognition for excellence in my field");
INSERT INTO Categories VALues("Using my skills/gifts to help people");
insert into Categories values("Building financial security/stability");
insert into Categories values("Leading a large organization");
insert into Categories values("Serving the public via elected office or appointment");
insert into Categories values("Accumulating significant financial wealth");
insert into Categories values("Traveling");
insert into Categories values("Maintaining physical health and fitness");
insert into Categories values("Contributing to the well-being of the community in which I live");
insert into Categories values("Paying off loans");
insert into Categories values("Sharing life with a committed partner");
insert into Categories values("Being a lifelong learner");
insert into Categories values("Raising children");
insert into Categories values("Having close personal relationships with friends");
insert into Categories values("Retiring Comfortably");
